export const mockSensors = [
  { id: "temp_001", name: "燃焼温度", path: "ボイラー/燃焼室/温度" },
  { id: "temp_002", name: "排ガス温度", path: "ボイラー/排気/温度" },
  { id: "press_001", name: "蒸気圧力", path: "ボイラー/蒸気/圧力" },
  { id: "flow_001", name: "給水流量", path: "ボイラー/給水/流量" },
  { id: "level_001", name: "水位", path: "ボイラー/ドラム/水位" },
  { id: "temp_003", name: "給水温度", path: "ボイラー/給水/温度" },
  { id: "temp_004", name: "蒸気温度", path: "ボイラー/蒸気/温度" },
  { id: "press_002", name: "燃焼圧力", path: "ボイラー/燃焼室/圧力" },
  { id: "flow_002", name: "燃料流量", path: "ボイラー/燃料/流量" },
  { id: "flow_003", name: "蒸気流量", path: "ボイラー/蒸気/流量" },
  { id: "temp_005", name: "外気温度", path: "環境/外気/温度" },
  { id: "humid_001", name: "外気湿度", path: "環境/外気/湿度" },
  { id: "press_003", name: "大気圧", path: "環境/外気/圧力" },
  { id: "temp_006", name: "室内温度", path: "環境/室内/温度" },
  { id: "humid_002", name: "室内湿度", path: "環境/室内/湿度" },
  { id: "power_001", name: "消費電力", path: "電力/消費/電力" },
  { id: "current_001", name: "電流値", path: "電力/消費/電流" },
  { id: "voltage_001", name: "電圧値", path: "電力/消費/電圧" },
  { id: "vibration_001", name: "振動値", path: "機械/振動/値" },
  { id: "noise_001", name: "騒音値", path: "機械/騒音/値" },
  { id: "rpm_001", name: "回転数", path: "機械/モーター/回転数" },
  { id: "torque_001", name: "トルク", path: "機械/モーター/トルク" },
  { id: "ph_001", name: "pH値", path: "水質/pH/値" },
  { id: "conductivity_001", name: "導電率", path: "水質/導電率/値" },
  { id: "oxygen_001", name: "溶存酸素", path: "水質/溶存酸素/値" },
]
